package com.assignment.UniversityEventManagement.model;

public enum Department {
    MECHANICAL, ELECTRICAL, CIVIL, CHEMICAL, COMPUTER, AEROSPACE, INDUSTRIAL, MATERIALS,
    ENVIRONMENTAL, BIOMEDICAL, PETROLEUM, NANOTECHNOLOGY, SYSTEMS, SOFTWARE
}
